*/Loading the data and calling it 'shoes'*///;
data shoes; 
	set SASHELP.SHOES;
run;
*///Removing any duplicates//;
proc sort data=shoes nodupkey out=shoes1;
	by Region Product Subsidiary Stores Sales Inventory Returns; 
run; 
*//Keeping only the following columns: Regions, Sales and Stores//;
data shoes2; 
	set shoes1(keep= Region Sales Stores);
run; 
*//Creating a table on sales and the number of stores for each region. Sorting the result by descending order of sales in a particular region//;
proc means data=shoes2 sum noprint;
  class Region;
  var Stores Sales;
  output out=region_summary(drop=_type_ _freq_) sum=SumStores SumSales;
  proc sort data=region_summary;
  by descending SumStores;
run;
